export const data = [
  { name: "Afghanistan", code: "af", country: "004" },
  { name: "Åland Islands", code: "ax", country: "248" },
  { name: "Albania", code: "al", country: "008" },
  { name: "Algeria", code: "dz", country: "012" },
  { name: "American Samoa", code: "as", country: "016" },
  { name: "Andorra", code: "ad", country: "020" },
  { name: "Angola", code: "ao", country: "024" },
  { name: "Anguilla", code: "ai", country: "660" },
  { name: "Antarctica", code: "aq", country: "010" },
  { name: "Antigua and Barbuda", code: "ag", country: "028" },
  { name: "Argentina", code: "ar", country: "032" },
  { name: "Armenia", code: "am", country: "051" },
  { name: "Aruba", code: "aw", country: "533" },
  { name: "Australia", code: "au", country: "036" },
  { name: "Austria", code: "at", country: "040" },
  { name: "Azerbaijan", code: "az", country: "031" },
  { name: "Bahamas", code: "bs", country: "044" },
  { name: "Bahrain", code: "bh", country: "048" },
  { name: "Bangladesh", code: "bd", country: "050" },
  { name: "Barbados", code: "bb", country: "052" },
  { name: "Belarus", code: "by", country: "112" },
  { name: "Belgium", code: "be", country: "056" },
  { name: "Belize", code: "bz", country: "084" },
  { name: "Benin", code: "bj", country: "204" },
  { name: "Bermuda", code: "bm", country: "060" },
  { name: "Bhutan", code: "bt", country: "064" },
  {
    name: "Bolivia (Plurinational State of)",
    code: "bo",
    country: "068",
  },
  {
    name: "Bonaire, Sint Eustatius and Saba",
    code: "bq",
    country: "535",
  },
  { name: "Bosnia and Herzegovina", code: "ba", country: "070" },
  { name: "Botswana", code: "bw", country: "072" },
  { name: "Bouvet Island", code: "bv", country: "074" },
  { name: "Brazil", code: "br", country: "076" },
  {
    name: "British Indian Ocean Territory",
    code: "io",
    country: "086",
  },
  { name: "Brunei Darussalam", code: "bn", country: "096" },
  { name: "Bulgaria", code: "bg", country: "100" },
  { name: "Burkina Faso", code: "bf", country: "854" },
  { name: "Burundi", code: "bi", country: "108" },
  { name: "Cabo Verde", code: "cv", country: "132" },
  { name: "Cambodia", code: "kh", country: "116" },
  { name: "Cameroon", code: "cm", country: "120" },
  { name: "Canada", code: "ca", country: "124" },
  { name: "Cayman Islands", code: "ky", country: "136" },
  { name: "Central African Republic", code: "cf", country: "140" },
  { name: "Chad", code: "td", country: "148" },
  { name: "Chile", code: "cl", country: "152" },
  { name: "China", code: "cn", country: "156" },
  { name: "Christmas Island", code: "cx", country: "162" },
  { name: "Cocos (Keeling) Islands", code: "cc", country: "166" },
  { name: "Colombia", code: "co", country: "170" },
  { name: "Comoros", code: "km", country: "174" },
  { name: "Congo", code: "cg", country: "178" },
  {
    name: "Congo, Democratic Republic of the",
    code: "cd",
    country: "180",
  },
  { name: "Cook Islands", code: "ck", country: "184" },
  { name: "Costa Rica", code: "cr", country: "188" },
  { name: "Côte d'Ivoire", code: "ci", country: "384" },
  { name: "Croatia", code: "hr", country: "191" },
  { name: "Cuba", code: "cu", country: "192" },
  { name: "Curaçao", code: "cw", country: "531" },
  { name: "Cyprus", code: "cy", country: "196" },
  { name: "Czechia", code: "cz", country: "203" },
  { name: "Denmark", code: "dk", country: "208" },
  { name: "Djibouti", code: "dj", country: "262" },
  { name: "Dominica", code: "dm", country: "212" },
  { name: "Dominican Republic", code: "do", country: "214" },
  { name: "Ecuador", code: "ec", country: "218" },
  { name: "Egypt", code: "eg", country: "818" },
  { name: "El Salvador", code: "sv", country: "222" },
  { name: "Equatorial Guinea", code: "gq", country: "226" },
  { name: "Eritrea", code: "er", country: "232" },
  { name: "Estonia", code: "ee", country: "233" },
  { name: "Eswatini", code: "sz", country: "748" },
  { name: "Ethiopia", code: "et", country: "231" },
  {
    name: "Falkland Islands (Malvinas)",
    code: "fk",
    country: "238",
  },
  { name: "Faroe Islands", code: "fo", country: "234" },
  { name: "Fiji", code: "fj", country: "242" },
  { name: "Finland", code: "fi", country: "246" },
  { name: "France", code: "fr", country: "250" },
  { name: "French Guiana", code: "gf", country: "254" },
  { name: "French Polynesia", code: "pf", country: "258" },
  {
    name: "French Southern Territories",
    code: "tf",
    country: "260",
  },
  { name: "Gabon", code: "ga", country: "266" },
  { name: "Gambia", code: "gm", country: "270" },
  { name: "Georgia", code: "ge", country: "268" },
  { name: "Germany", code: "de", country: "276" },
  { name: "Ghana", code: "gh", country: "288" },
  { name: "Gibraltar", code: "gi", country: "292" },
  { name: "Greece", code: "gr", country: "300" },
  { name: "Greenland", code: "gl", country: "304" },
  { name: "Grenada", code: "gd", country: "308" },
  { name: "Guadeloupe", code: "gp", country: "312" },
  { name: "Guam", code: "gu", country: "316" },
  { name: "Guatemala", code: "gt", country: "320" },
  { name: "Guernsey", code: "gg", country: "831" },
  { name: "Guinea", code: "gn", country: "324" },
  { name: "Guinea-Bissau", code: "gw", country: "624" },
  { name: "Guyana", code: "gy", country: "328" },
  { name: "Haiti", code: "ht", country: "332" },
  {
    name: "Heard Island and McDonald Islands",
    code: "hm",
    country: "334",
  },
  { name: "Holy See", code: "va", country: "336" },
  { name: "Honduras", code: "hn", country: "340" },
  { name: "Hong Kong", code: "hk", country: "344" },
  { name: "Hungary", code: "hu", country: "348" },
  { name: "Iceland", code: "is", country: "352" },
  { name: "India", code: "in", country: "356" },
  { name: "Indonesia", code: "id", country: "360" },
  {
    name: "Iran (Islamic Republic of)",
    code: "ir",
    country: "364",
  },
  { name: "Iraq", code: "iq", country: "368" },
  { name: "Ireland", code: "ie", country: "372" },
  { name: "Isle of Man", code: "im", country: "833" },
  { name: "Israel", code: "il", country: "376" },
  { name: "Italy", code: "it", country: "380" },
  { name: "Jamaica", code: "jm", country: "388" },
  { name: "Japan", code: "jp", country: "392" },
  { name: "Jersey", code: "je", country: "832" },
  { name: "Jordan", code: "jo", country: "400" },
  { name: "Kazakhstan", code: "kz", country: "398" },
  { name: "Kenya", code: "ke", country: "404" },
  { name: "Kiribati", code: "ki", country: "296" },
  {
    name: "Korea (Democratic People's Republic of)",
    code: "kp",
    country: "408",
  },
  { name: "Korea, Republic of", code: "kr", country: "410" },
  { name: "Kuwait", code: "kw", country: "414" },
  { name: "Kyrgyzstan", code: "kg", country: "417" },
  {
    name: "Lao People's Democratic Republic",
    code: "la",
    country: "418",
  },
  { name: "Latvia", code: "lv", country: "428" },
  { name: "Lebanon", code: "lb", country: "422" },
  { name: "Lesotho", code: "ls", country: "426" },
  { name: "Liberia", code: "lr", country: "430" },
  { name: "Libya", code: "ly", country: "434" },
  { name: "Liechtenstein", code: "li", country: "438" },
  { name: "Lithuania", code: "lt", country: "440" },
  { name: "Luxembourg", code: "lu", country: "442" },
  { name: "Macao", code: "mo", country: "446" },
  { name: "Madagascar", code: "mg", country: "450" },
  { name: "Malawi", code: "mw", country: "454" },
  { name: "Malaysia", code: "my", country: "458" },
  { name: "Maldives", code: "mv", country: "462" },
  { name: "Mali", code: "ml", country: "466" },
  { name: "Malta", code: "mt", country: "470" },
  { name: "Marshall Islands", code: "mh", country: "584" },
  { name: "Martinique", code: "mq", country: "474" },
  { name: "Mauritania", code: "mr", country: "478" },
  { name: "Mauritius", code: "mu", country: "480" },
  { name: "Mayotte", code: "yt", country: "175" },
  { name: "Mexico", code: "mx", country: "484" },
  {
    name: "Micronesia (Federated States of)",
    code: "fm",
    country: "583",
  },
  { name: "Moldova, Republic of", code: "md", country: "498" },
  { name: "Monaco", code: "mc", country: "492" },
  { name: "Mongolia", code: "mn", country: "496" },
  { name: "Montenegro", code: "me", country: "499" },
  { name: "Montserrat", code: "ms", country: "500" },
  { name: "Morocco", code: "ma", country: "504" },
  { name: "Mozambique", code: "mz", country: "508" },
  { name: "Myanmar", code: "mm", country: "104" },
  { name: "Namibia", code: "na", country: "516" },
  { name: "Nauru", code: "nr", country: "520" },
  { name: "Nepal", code: "np", country: "524" },
  { name: "Netherlands", code: "nl", country: "528" },
  { name: "New Caledonia", code: "nc", country: "540" },
  { name: "New Zealand", code: "nz", country: "554" },
  { name: "Nicaragua", code: "ni", country: "558" },
  { name: "Niger", code: "ne", country: "562" },
  { name: "Nigeria", code: "ng", country: "566" },
  { name: "Niue", code: "nu", country: "570" },
  { name: "Norfolk Island", code: "nf", country: "574" },
  { name: "North Macedonia", code: "mk", country: "807" },
  { name: "Northern Mariana Islands", code: "mp", country: "580" },
  { name: "Norway", code: "no", country: "578" },
  { name: "Oman", code: "om", country: "512" },
  { name: "Pakistan", code: "pk", country: "586" },
  { name: "Palau", code: "pw", country: "585" },
  { name: "Palestine, State of", code: "ps", country: "275" },
  { name: "Panama", code: "pa", country: "591" },
  { name: "Papua New Guinea", code: "pg", country: "598" },
  { name: "Paraguay", code: "py", country: "600" },
  { name: "Peru", code: "pe", country: "604" },
  { name: "Philippines", code: "ph", country: "608" },
  { name: "Pitcairn", code: "pn", country: "612" },
  { name: "Poland", code: "pl", country: "616" },
  { name: "Portugal", code: "pt", country: "620" },
  { name: "Puerto Rico", code: "pr", country: "630" },
  { name: "Qatar", code: "qa", country: "634" },
  { name: "Réunion", code: "re", country: "638" },
  { name: "Romania", code: "ro", country: "642" },
  { name: "Russian Federation", code: "ru", country: "643" },
  { name: "Rwanda", code: "rw", country: "646" },
  { name: "Saint Barthélemy", code: "bl", country: "652" },
  {
    name: "Saint Helena, Ascension and Tristan da Cunha",
    code: "sh",
    country: "654",
  },
  { name: "Saint Kitts and Nevis", code: "kn", country: "659" },
  { name: "Saint Lucia", code: "lc", country: "662" },
  {
    name: "Saint Martin (French part)",
    code: "mf",
    country: "663",
  },
  { name: "Saint Pierre and Miquelon", code: "pm", country: "666" },
  {
    name: "Saint Vincent and the Grenadines",
    code: "vc",
    country: "670",
  },
  { name: "Samoa", code: "ws", country: "882" },
  { name: "San Marino", code: "sm", country: "674" },
  { name: "Sao Tome and Principe", code: "st", country: "678" },
  { name: "Saudi Arabia", code: "sa", country: "682" },
  { name: "Senegal", code: "sn", country: "686" },
  { name: "Serbia", code: "rs", country: "688" },
  { name: "Seychelles", code: "sc", country: "690" },
  { name: "Sierra Leone", code: "sl", country: "694" },
  { name: "Singapore", code: "sg", country: "702" },
  { name: "Sint Maarten (Dutch part)", code: "sx", country: "534" },
  { name: "Slovakia", code: "sk", country: "703" },
  { name: "Slovenia", code: "si", country: "705" },
  { name: "Solomon Islands", code: "sb", country: "090" },
  { name: "Somalia", code: "so", country: "706" },
  { name: "South Africa", code: "za", country: "710" },
  {
    name: "South Georgia and the South Sandwich Islands",
    code: "gs",
    country: "239",
  },
  { name: "South Sudan", code: "ss", country: "728" },
  { name: "Spain", code: "es", country: "724" },
  { name: "Sri Lanka", code: "lk", country: "144" },
  { name: "Sudan", code: "sd", country: "729" },
  { name: "Suriname", code: "sr", country: "740" },
  { name: "Svalbard and Jan Mayen", code: "sj", country: "744" },
  { name: "Sweden", code: "se", country: "752" },
  { name: "Switzerland", code: "ch", country: "756" },
  { name: "Syrian Arab Republic", code: "sy", country: "760" },
  { name: "Taiwan, Province of China", code: "tw", country: "158" },
  { name: "Tajikistan", code: "tj", country: "762" },
  {
    name: "Tanzania, United Republic of",
    code: "tz",
    country: "834",
  },
  { name: "Thailand", code: "th", country: "764" },
  { name: "Timor-Leste", code: "tl", country: "626" },
  { name: "Togo", code: "tg", country: "768" },
  { name: "Tokelau", code: "tk", country: "772" },
  { name: "Tonga", code: "to", country: "776" },
  { name: "Trinidad and Tobago", code: "tt", country: "780" },
  { name: "Tunisia", code: "tn", country: "788" },
  { name: "Turkey", code: "tr", country: "792" },
  { name: "Turkmenistan", code: "tm", country: "795" },
  { name: "Turks and Caicos Islands", code: "tc", country: "796" },
  { name: "Tuvalu", code: "tv", country: "798" },
  { name: "Uganda", code: "ug", country: "800" },
  { name: "Ukraine", code: "ua", country: "804" },
  { name: "United Arab Emirates", code: "ae", country: "784" },
  {
    name: "United Kingdom of Great Britain and Northern Ireland",
    code: "gb",
    country: "826",
  },
  { name: "United States of America", code: "us", country: "840" },
  {
    name: "United States Minor Outlying Islands",
    code: "um",
    country: "581",
  },
  { name: "Uruguay", code: "uy", country: "858" },
  { name: "Uzbekistan", code: "uz", country: "860" },
  { name: "Vanuatu", code: "uv", country: "548" },
  {
    name: "Venezuela (Bolivarian Republic of)",
    code: "ve",
    country: "862",
  },
  { name: "Viet Nam", code: "vn", country: "704" },
  { name: "Virgin Islands (British)", code: "vg", country: "092" },
  { name: "Virgin Islands (U.S.)", code: "vi", country: "850" },
  { name: "Wallis and Futuna", code: "wf", country: "876" },
  { name: "Western Sahara", code: "eh", country: "732" },
  { name: "Yemen", code: "ye", country: "887" },
  { name: "Zambia", code: "zm", country: "894" },
  { name: "Zimbabwe", code: "zw", country: "716" },
];
    